name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # ========== Linux сборка с GCC и Clang ==========
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        build_type: [Release, Debug]
    steps:
    - uses: actions/checkout@v3
    - name: Install CMake
      run: sudo apt-get install -y cmake
    - name: Configure
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    - name: Build
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }}
    - name: Run hello_world
      run: ./build/hello_world_application/hello_world
    - name: Run equation
      run: echo "1 -3 2" | ./build/solver_application/equation

  # ========== Windows сборка ==========
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Release, Debug]
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    - name: Build
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }}
    - name: Run hello_world
      run: ./build/hello_world_application/${{ matrix.build_type }}/hello_world.exe
    - name: Run equation
      shell: cmd
      run: echo 1 -3 2 | ./build/solver_application/${{ matrix.build_type }}/equation.exe
